import '../widgets/productModel.dart';

final List<Product> demoProducts = [
  // ===== Cement =====
  Product(
    id: 1,
    name: 'Premium Portland Cement',
    category: 'Cement',
    price: 350,
    unit: 'per bag (50kg)',
    image: '🏗️',
    description: 'Premium quality Portland cement',
    detailedDescription:
        'High-quality Portland Pozzolana Cement (PPC) ideal for all construction needs. Superior strength and durability. Conforms to IS 1489 standards. Perfect for residential and commercial projects.',
    deliveryPricePerKm: 5,
    dealer: 'ABC Cement Co.',
    dealerLocation: 'New Delhi',
  ),
  Product(
    id: 2,
    name: 'Ultratech Cement',
    category: 'Cement',
    price: 380,
    unit: 'per bag (50kg)',
    image: '🏗️',
    description: 'Ultratech PPC cement for strong construction',
    detailedDescription:
        'Ultratech Portland Pozzolana Cement (PPC) with enhanced durability and workability. Ideal for plastering and brickwork. Provides excellent finish and strength.',
    deliveryPricePerKm: 5,
    dealer: 'XYZ Cement Co.',
    dealerLocation: 'Mumbai',
  ),
  Product(
    id: 3,
    name: 'ACC Gold Cement',
    category: 'Cement',
    price: 365,
    unit: 'per bag (50kg)',
    image: '🏗️',
    description: 'ACC Gold water-resistant cement',
    detailedDescription:
        'ACC Gold cement with advanced water-resistant formula. Perfect for areas with high moisture. Provides superior bonding and durability.',
    deliveryPricePerKm: 5,
    dealer: 'PQR Cement Co.',
    dealerLocation: 'Chennai',
  ),
  Product(
    id: 4,
    name: 'Ambuja Cement',
    category: 'Cement',
    price: 355,
    unit: 'per bag (50kg)',
    image: '🏗️',
    description: 'Ambuja strong concrete cement',
    detailedDescription:
        'Ambuja cement known for its strength and quality. Ideal for foundations and structural work. Meets all international quality standards.',
    deliveryPricePerKm: 5,
    dealer: 'LMN Cement Co.',
    dealerLocation: 'Kolkata',
  ),

  // ===== Sand =====
  Product(
    id: 5,
    name: 'River Sand',
    category: 'Sand',
    price: 45,
    unit: 'per cubic foot',
    image: '🏖️',
    description: 'Fine quality river sand',
    detailedDescription:
        'Premium washed river sand, free from impurities and organic matter. Ideal for plastering, concreting, and masonry work. Consistent grain size for optimal concrete mix.',
    deliveryPricePerKm: 3,
    dealer: 'ABC Sand Co.',
    dealerLocation: 'New Delhi',
  ),
  Product(
    id: 6,
    name: 'M-Sand (Manufactured Sand)',
    category: 'Sand',
    price: 40,
    unit: 'per cubic foot',
    image: '🏖️',
    description: 'Eco-friendly manufactured sand',
    detailedDescription:
        'High-quality manufactured sand as a sustainable alternative to river sand. Consistent quality and better bonding strength. Ideal for all construction purposes.',
    deliveryPricePerKm: 3,
    dealer: 'XYZ Sand Co.',
    dealerLocation: 'Mumbai',
  ),
  Product(
    id: 7,
    name: 'Plastering Sand',
    category: 'Sand',
    price: 42,
    unit: 'per cubic foot',
    image: '🏖️',
    description: 'Fine sand for smooth plastering',
    detailedDescription:
        'Specially graded fine sand perfect for plastering work. Provides smooth finish and excellent adhesion. Free from clay and silt content.',
    deliveryPricePerKm: 3,
    dealer: 'PQR Sand Co.',
    dealerLocation: 'Chennai',
  ),
  Product(
    id: 8,
    name: 'Concrete Sand',
    category: 'Sand',
    price: 48,
    unit: 'per cubic foot',
    image: '🏖️',
    description: 'Coarse sand for concrete mixing',
    detailedDescription:
        'Premium coarse sand ideal for concrete mixing. Provides excellent strength and durability. Perfect grain size distribution for optimal concrete quality.',
    deliveryPricePerKm: 3,
    dealer: 'LMN Sand Co.',
    dealerLocation: 'Kolkata',
  ),

  // ===== Steel / Iron Rod =====
  Product(
    id: 9,
    name: 'TMT Steel Bars - 8mm',
    category: 'Iron Rod',
    price: 65,
    unit: 'per kg',
    image: '⚒️',
    description: '8mm TMT steel bars',
    detailedDescription:
        'Fe 500D grade TMT bars (8mm) with superior tensile strength and ductility. Earthquake resistant and corrosion proof. ISI certified. Ideal for light construction work.',
    deliveryPricePerKm: 8,
    dealer: 'ABC Steel Co.',
    dealerLocation: 'New Delhi',
  ),
  Product(
    id: 10,
    name: 'TMT Steel Bars - 12mm',
    category: 'Iron Rod',
    price: 67,
    unit: 'per kg',
    image: '⚒️',
    description: '12mm TMT steel bars',
    detailedDescription:
        'Fe 500D grade TMT bars (12mm) for medium construction needs. Excellent bendability and weldability. Perfect for residential construction and columns.',
    deliveryPricePerKm: 8,
    dealer: 'XYZ Steel Co.',
    dealerLocation: 'Mumbai',
  ),
  Product(
    id: 11,
    name: 'TMT Steel Bars - 16mm',
    category: 'Iron Rod',
    price: 68,
    unit: 'per kg',
    image: '⚒️',
    description: '16mm TMT steel bars',
    detailedDescription:
        'Fe 500D grade TMT bars (16mm) for heavy-duty construction. High strength and durability. Ideal for beams, slabs, and heavy structural work.',
    deliveryPricePerKm: 8,
    dealer: 'PQR Steel Co.',
    dealerLocation: 'Chennai',
  ),
  Product(
    id: 12,
    name: 'TMT Steel Bars - 20mm',
    category: 'Iron Rod',
    price: 70,
    unit: 'per kg',
    image: '⚒️',
    description: '20mm TMT steel bars for heavy structures',
    detailedDescription:
        'Fe 500D grade TMT bars (20mm) for heavy structural applications. Maximum strength and load-bearing capacity. Perfect for commercial buildings and bridges.',
    deliveryPricePerKm: 8,
    dealer: 'LMN Steel Co.',
    dealerLocation: 'Kolkata',
  ),
];
